apiVersion: apps/v1
kind: Deployment
metadata:
  name: query
  labels:
    app:  query
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  query
  template:
    metadata:
      labels:
        app:  query
    spec:
      containers:
      - name: query
        image: aishwaryaa/query
  
---
kind: Service
apiVersion: v1
metadata:
  name:  query-serv
spec:
  selector:
    app:  query
  # type:  LoadBalancer | ClusterIP | NodePort
  ports:
  - protocol:  TCP
    port:  4003
    targetPort:  4003